server:
  port: 9104
spring:
  application:
    name: nacos-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
com:
  tony:
    name: tonychen
    pwd: 123456
    age: 20